Working bitrise.yml.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -8,38 +8,58 @@ trigger_map:
 - pull_request_source_branch: "*"
   workflow: primary
 workflows:
-  deploy:
+  update:
     steps:
-    - activate-ssh-key@4:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@4: {}
-    - cache-pull@2: {}
-    - certificate-and-profile-installer@1: {}
-    - recreate-user-schemes@1:
+    - script@1:
         inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-    - xcode-archive@3:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            bitrise update --version 1.50.0
+        title: Update Bitrise CLI
+    - script@1:
         inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-        - scheme: "$BITRISE_SCHEME"
-        - force_code_sign_identity: "$BITRISE_CODE_SIGNING_IDENTITY"
-        - force_provisioning_profile: "$BITRISE_PROFILE_ID"
-        - compile_bitcode: 'no'
-        - upload_bitcode: 'no'
-        - team_id: "$BITRISE_TEAM"
-        - export_method: "$BITRISE_EXPORT_METHOD"
-    - deploy-to-bitrise-io@1: {}
-    - cache-push@2: {}
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            bitrise version
+        title: Verify CLI Version
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
+
+            dir=$(find /var/folders/4x/p4lcqjn532v7c7n456nsp00h0000gn/T -maxdepth 1 -type d -name 'bitrise-agent*')
+
+            bitrise run --config ${dir}/bitrise.yml primary
+        title: Kick off Primary WF
   primary:
     steps:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git::https://github.com/matrangam/bitrise-step-swift-clone.git@main:
         inputs:
-        - repository_url: "https://github.com/bitrise-io/Bitrise-iOS-Sample"
-        - clone_destination: "./_tmp"
-        - checkout_branch: "mm/cleanup"
-        - clone_depth: "1"
+        - repository_url: https://github.com/bitrise-io/Bitrise-iOS-Sample
+        - checkout_branch: mm/cleanup
+        - clone_depth: '1'
     - cache-pull@2: {}
     - certificate-and-profile-installer@1: {}
     - xcode-test@2:
@@ -52,7 +72,7 @@ app:
   envs:
   - opts:
       is_expand: false
-    BITRISE_PROJECT_PATH: BitriseTest.xcodeproj
+    BITRISE_PROJECT_PATH: Bitrise-iOS-Sample/BitriseTest.xcodeproj
   - opts:
       is_expand: false
     BITRISE_SCHEME: BitriseTest
@@ -68,3 +88,10 @@ app:
   - opts:
       is_expand: false
     BITRISE_TEAM: 72SA8V3WYL
+  - opts:
+      is_expand: false
+    BITRISE_CODE_SIGNING_IDENTITY: 'iPhone Developer: Dev Portal Bot Bitrise (E89JV3W9K4)'
+meta:
+  bitrise.io:
+    stack: osx-xcode-14.0.x
+    machine_type_id: g2-m1.8core
